# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @useDynLib MSA2dist, .registration = TRUE
#' @import Rcpp
#' @title rcpp_KaKs
#' @name rcpp_KaKs
#' @description calculates KaKs as implememted in
#' KaKs Calculator 2.0 \code{MSA2dist} with \code{Rcpp}.
#' @return \code{list}
#' @param cdsstr StringVector [mandatory]
#' @param sgc standard genetic code to use [default: 1]
#' @param method KaKs Calculator 2.0 codon model [default: YN]
#' @param verbose specify if verbose output [default: FALSE]
#' @references Wang et al. (2010) KaKs_Calculator 2.0: a toolkit incorporating
#' gamma-series methods and sliding window strategies.\emph{Genomics,
#' proteomics & bioinformatics.} \bold{8(1)}, 77-80.
#' @examples
#' ## load example sequence data
#' data("hiv", package="MSA2dist")
#' rcpp_KaKs(cdsstr=as.character(hiv[1:3]))
#' @export rcpp_KaKs
#' @author Kristian K Ullrich
rcpp_KaKs <- function(cdsstr, sgc = "1", method = "YN", verbose = FALSE) {
    .Call(`_MSA2dist_rcpp_KaKs`, cdsstr, sgc, method, verbose)
}

#' @useDynLib MSA2dist, .registration = TRUE
#' @import Rcpp
#' @title rcpp_distSTRING
#' @name rcpp_distSTRING
#' @description calculates pairwise distances using a score matrix
#' @return list containing:
#' \itemize{
#'     \item distSTRING
#'     \item sitesUsed
#' }
#' @param dnavector StringVector [mandatory]
#' @param scoreMatrix NumericMatrix [mandatory]
#' @param ncores number of cores [default: 1]
#' @param symmetric symmetric score matrix [default: 1]
#' @examples
#' ## load example sequence data
#' data("hiv", package="MSA2dist")
#' rcpp_distSTRING(dnavector=as.character(hiv), scoreMatrix=iupacMatrix())
#' @export rcpp_distSTRING
#' @author Kristian K Ullrich
rcpp_distSTRING <- function(dnavector, scoreMatrix,
    ncores = 1L, symmetric = 1L) {
    .Call(`_MSA2dist_rcpp_distSTRING`, dnavector, scoreMatrix,
    ncores, symmetric)
}

#' @useDynLib MSA2dist, .registration = TRUE
#' @import Rcpp
#' @title rcpp_dxy_fst_pop
#' @name rcpp_dxy_fst_pop
#' @description calculates dxy and fst per population combination
#' @return list containing:
#' \itemize{
#'     \item dxy
#'     \item fst
#'     \item pi_within
#'     \item pi_between
#'     \item populations
#'     \item model
#'     \item estimator
#' }
#' @param dnavector StringVector [mandatory]
#' @param pop_idx IntegerVector [mandatory]
#' @param model string [default: IUPAC]
#' @param estimator string [default: count]
#' @examples
#' ## load example sequence data
#' data("iupac", package="MSA2dist")
#' rcpp_dxy_fst_pop(dnavector=as.character(iupac),
#' pop_idx=c(rep(1,8),rep(2,8),rep(3,8),rep(4,6)),
#' model="IUPAC",
#' estimator="count")
#' rcpp_dxy_fst_pop(dnavector=as.character(iupac),
#' pop_idx=c(rep(1,8),rep(2,8),rep(3,8),rep(4,6)),
#' model="IUPAC",
#' estimator="prob")
#' rcpp_dxy_fst_pop(dnavector=as.character(iupac),
#' pop_idx=c(rep(1,8),rep(2,8),rep(3,8),rep(4,6)),
#' model="sequence",
#' estimator="count")
#' rcpp_dxy_fst_pop(dnavector=as.character(iupac),
#' pop_idx=c(rep(1,8),rep(2,8),rep(3,8),rep(4,6)),
#' model="sequence",
#' estimator="prob")
#' @export rcpp_dxy_fst_pop
#' @author Kristian K Ullrich
rcpp_dxy_fst_pop <- function(dnavector, pop_idx, model = "IUPAC",
    estimator = "prob") {
    .Call(`_MSA2dist_rcpp_dxy_fst_pop`, dnavector, pop_idx, model, 
    estimator)
}

#' @useDynLib MSA2dist, .registration = TRUE
#' @import Rcpp
#' @title rcpp_pairwiseDeletionAA
#' @name rcpp_pairwiseDeletionAA
#' @description returns number of AA sites used
#' @return list containing:
#' \itemize{
#'     \item sitesUsed
#' }
#' @param aavector StringVector [mandatory]
#' @param ncores number of cores [default: 1]
#' @param symmetric symmetric score matrix [default: 1]
#' @examples
#' ## load example sequence data
#' data("hiv", package="MSA2dist")
#' h <- hiv |> cds2aa() |> as.character()
#' rcpp_pairwiseDeletionAA(aavector=h, ncores=1)
#' @export rcpp_pairwiseDeletionAA
#' @author Kristian K Ullrich
rcpp_pairwiseDeletionAA <- function(aavector, ncores = 1L, symmetric = 1L) {
    .Call(`_MSA2dist_rcpp_pairwiseDeletionAA`, aavector, ncores, symmetric)
}

#' @useDynLib MSA2dist, .registration = TRUE
#' @import Rcpp
#' @title rcpp_pairwiseDeletionDNA
#' @name rcpp_pairwiseDeletionDNA
#' @description returns number of DNA sites used
#' @return list containing:
#' \itemize{
#'     \item sitesUsed
#' }
#' @param dnavector StringVector [mandatory]
#' @param ncores number of cores [default: 1]
#' @param symmetric symmetric score matrix [default: 1]
#' @examples
#' ## load example sequence data
#' data("woodmouse", package="ape")
#' w <- woodmouse |> dnabin2dnastring() |> as.character()
#' rcpp_pairwiseDeletionDNA(dnavector=w, ncores=1)
#' @export rcpp_pairwiseDeletionDNA
#' @author Kristian K Ullrich
rcpp_pairwiseDeletionDNA <- function(dnavector, ncores = 1L, symmetric = 1L) {
    .Call(`_MSA2dist_rcpp_pairwiseDeletionDNA`, dnavector, ncores, symmetric)
}

#' @useDynLib MSA2dist, .registration = TRUE
#' @import Rcpp
#' @title rcpp_weightedPi
#' @name rcpp_weightedPi
#' @description calculates weighted pi
#' @return list containing:
#' \itemize{
#'     \item weightedPi
#'     \item model
#'     \item estimator
#' }
#' @param dnavector StringVector [mandatory]
#' @param model string [default: IUPAC]
#' @param estimator string [default: count]
#' @examples
#' ## load example sequence data
#' data("hiv", package="MSA2dist")
#' rcpp_weightedPi(dnavector=as.character(hiv), model="IUPAC",
#' estimator="count")
#' rcpp_weightedPi(dnavector=as.character(hiv), model="sequence",
#' estimator="count")
#' rcpp_weightedPi(dnavector=as.character(hiv), model="IUPAC",
#' estimator="prob")
#' rcpp_weightedPi(dnavector=as.character(hiv), model="sequence",
#' estimator="prob")
#' @export rcpp_weightedPi
#' @author Kristian K Ullrich
rcpp_weightedPi <- function(dnavector, model = "IUPAC", estimator = "count") {
    .Call(`_MSA2dist_rcpp_weightedPi`, dnavector, model, estimator)
}

#' @useDynLib MSA2dist, .registration = TRUE
#' @import Rcpp
#' @title rcpp_weightedPi_pop
#' @name rcpp_weightedPi_pop
#' @description calculates weighted pi per population
#' @return list containing:
#' \itemize{
#'     \item weightedPi
#'     \item populations
#'     \item model
#'     \item estimator
#' }
#' @param dnavector StringVector [mandatory]
#' @param pop_idx IntegerVector [mandatory]
#' @param model string [default: IUPAC]
#' @param estimator string [default: count]
#' @examples
#' ## load example sequence data
#' data("iupac", package="MSA2dist")
#' rcpp_weightedPi_pop(dnavector=as.character(iupac),
#' pop_idx=c(rep(1,8),rep(2,8),rep(3,8),rep(4,6)),
#' model="IUPAC",
#' estimator="count")
#' rcpp_weightedPi_pop(dnavector=as.character(iupac),
#' pop_idx=c(rep(1,8),rep(2,8),rep(3,8),rep(4,6)),
#' model="IUPAC",
#' estimator="prob")
#' rcpp_weightedPi_pop(dnavector=as.character(iupac),
#' pop_idx=c(rep(1,8),rep(2,8),rep(3,8),rep(4,6)),
#' model="sequence",
#' estimator="count")
#' rcpp_weightedPi_pop(dnavector=as.character(iupac),
#' pop_idx=c(rep(1,8),rep(2,8),rep(3,8),rep(4,6)),
#' model="sequence",
#' estimator="prob")
#' @export rcpp_weightedPi_pop
#' @author Kristian K Ullrich
rcpp_weightedPi_pop <- function(dnavector, pop_idx, model = "IUPAC",
    estimator = "count") {
    .Call(`_MSA2dist_rcpp_weightedPi_pop`, dnavector, pop_idx, model,
    estimator)
}

